/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/new_qcu_map.glb --types --verbose 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_tree_palmShort: THREE.Mesh
    Mesh_tree_palmShort_1: THREE.Mesh
    Mesh_tree_palmShort001: THREE.Mesh
    Mesh_tree_palmShort001_1: THREE.Mesh
    Mesh_tree_palmShort002: THREE.Mesh
    Mesh_tree_palmShort002_1: THREE.Mesh
    Mesh_tree_oak_dark: THREE.Mesh
    Mesh_tree_oak_dark_1: THREE.Mesh
    Mesh_tree_oak_dark001: THREE.Mesh
    Mesh_tree_oak_dark001_1: THREE.Mesh
    Mesh_tree_oak_dark002: THREE.Mesh
    Mesh_tree_oak_dark002_1: THREE.Mesh
    Mesh_tree_oak_dark003: THREE.Mesh
    Mesh_tree_oak_dark003_1: THREE.Mesh
    Mesh_tree_oak_dark004: THREE.Mesh
    Mesh_tree_oak_dark004_1: THREE.Mesh
    Mesh_tree_oak_dark005: THREE.Mesh
    Mesh_tree_oak_dark005_1: THREE.Mesh
    Mesh_tree_oak_dark006: THREE.Mesh
    Mesh_tree_oak_dark006_1: THREE.Mesh
    Mesh_tree_oak_dark007: THREE.Mesh
    Mesh_tree_oak_dark007_1: THREE.Mesh
    Mesh_tree_oak_dark008: THREE.Mesh
    Mesh_tree_oak_dark008_1: THREE.Mesh
    Mesh_tree_oak_dark009: THREE.Mesh
    Mesh_tree_oak_dark009_1: THREE.Mesh
    Mesh_tree_fat_darkh: THREE.Mesh
    Mesh_tree_fat_darkh_1: THREE.Mesh
    Mesh_tree_fat_darkh001: THREE.Mesh
    Mesh_tree_fat_darkh001_1: THREE.Mesh
    Mesh_tree_fat_darkh002: THREE.Mesh
    Mesh_tree_fat_darkh002_1: THREE.Mesh
    Mesh_tree_fat_darkh003: THREE.Mesh
    Mesh_tree_fat_darkh003_1: THREE.Mesh
    Mesh_tree_fat_darkh004: THREE.Mesh
    Mesh_tree_fat_darkh004_1: THREE.Mesh
    Mesh_tree_pineSmallA: THREE.Mesh
    Mesh_tree_pineSmallA_1: THREE.Mesh
    Mesh_tree_pineSmallA001: THREE.Mesh
    Mesh_tree_pineSmallA001_1: THREE.Mesh
    Mesh_tree_pineSmallA002: THREE.Mesh
    Mesh_tree_pineSmallA002_1: THREE.Mesh
    Mesh_tree_pineSmallA003: THREE.Mesh
    Mesh_tree_pineSmallA003_1: THREE.Mesh
    Mesh_tree_pineSmallA004: THREE.Mesh
    Mesh_tree_pineSmallA004_1: THREE.Mesh
    Mesh_tree_pineSmallA005: THREE.Mesh
    Mesh_tree_pineSmallA005_1: THREE.Mesh
    Mesh_tree_pineSmallA010: THREE.Mesh
    Mesh_tree_pineSmallA010_1: THREE.Mesh
    Mesh_tree_pineSmallA007: THREE.Mesh
    Mesh_tree_pineSmallA007_1: THREE.Mesh
    Mesh_tree_pineSmallA011: THREE.Mesh
    Mesh_tree_pineSmallA011_1: THREE.Mesh
    Mesh_tree_pineSmallA009: THREE.Mesh
    Mesh_tree_pineSmallA009_1: THREE.Mesh
    Mesh_tree_pineSmallA012: THREE.Mesh
    Mesh_tree_pineSmallA012_1: THREE.Mesh
    Mesh_tree_pineSmallA013: THREE.Mesh
    Mesh_tree_pineSmallA013_1: THREE.Mesh
    Mesh_tree_pineSmallA014: THREE.Mesh
    Mesh_tree_pineSmallA014_1: THREE.Mesh
    Mesh_tree_pineSmallA015: THREE.Mesh
    Mesh_tree_pineSmallA015_1: THREE.Mesh
    Mesh_tree_pineSmallA017: THREE.Mesh
    Mesh_tree_pineSmallA017_1: THREE.Mesh
    Mesh_tree_pineSmallA018: THREE.Mesh
    Mesh_tree_pineSmallA018_1: THREE.Mesh
    Mesh_tree_pineSmallA019: THREE.Mesh
    Mesh_tree_pineSmallA019_1: THREE.Mesh
    Mesh_tree_pineSmallA020: THREE.Mesh
    Mesh_tree_pineSmallA020_1: THREE.Mesh
    Mesh_tree_pineSmallA021: THREE.Mesh
    Mesh_tree_pineSmallA021_1: THREE.Mesh
    Mesh_tree_pineSmallA022: THREE.Mesh
    Mesh_tree_pineSmallA022_1: THREE.Mesh
    Mesh_tree_pineSmallA023: THREE.Mesh
    Mesh_tree_pineSmallA023_1: THREE.Mesh
    Mesh_tree_pineSmallA024: THREE.Mesh
    Mesh_tree_pineSmallA024_1: THREE.Mesh
    Mesh_tree_pineSmallA025: THREE.Mesh
    Mesh_tree_pineSmallA025_1: THREE.Mesh
    Mesh_tree_pineSmallA026: THREE.Mesh
    Mesh_tree_pineSmallA026_1: THREE.Mesh
    Mesh_tree_pineSmallA027: THREE.Mesh
    Mesh_tree_pineSmallA027_1: THREE.Mesh
    Mesh_tree_pineSmallA028: THREE.Mesh
    Mesh_tree_pineSmallA028_1: THREE.Mesh
    Mesh_tree_pineSmallA029: THREE.Mesh
    Mesh_tree_pineSmallA029_1: THREE.Mesh
    Mesh_tree_pineSmallA030: THREE.Mesh
    Mesh_tree_pineSmallA030_1: THREE.Mesh
    Mesh_tree_pineSmallA031: THREE.Mesh
    Mesh_tree_pineSmallA031_1: THREE.Mesh
    Mesh_tree_pineSmallA032: THREE.Mesh
    Mesh_tree_pineSmallA032_1: THREE.Mesh
    Mesh_tree_pineSmallA033: THREE.Mesh
    Mesh_tree_pineSmallA033_1: THREE.Mesh
    Mesh_tree_pineSmallA034: THREE.Mesh
    Mesh_tree_pineSmallA034_1: THREE.Mesh
    Mesh_tree_pineSmallA035: THREE.Mesh
    Mesh_tree_pineSmallA035_1: THREE.Mesh
    Mesh_tree_pineSmallA036: THREE.Mesh
    Mesh_tree_pineSmallA036_1: THREE.Mesh
    Mesh_tree_pineSmallA037: THREE.Mesh
    Mesh_tree_pineSmallA037_1: THREE.Mesh
    Mesh_tree_pineSmallA038: THREE.Mesh
    Mesh_tree_pineSmallA038_1: THREE.Mesh
    Mesh_tree_pineSmallA039: THREE.Mesh
    Mesh_tree_pineSmallA039_1: THREE.Mesh
    Mesh_tree_pineSmallA040: THREE.Mesh
    Mesh_tree_pineSmallA040_1: THREE.Mesh
    Mesh_tree_pineSmallA041: THREE.Mesh
    Mesh_tree_pineSmallA041_1: THREE.Mesh
    Mesh_tree_pineSmallA042: THREE.Mesh
    Mesh_tree_pineSmallA042_1: THREE.Mesh
    Mesh_tree_pineSmallA043: THREE.Mesh
    Mesh_tree_pineSmallA043_1: THREE.Mesh
    Mesh_tree_pineSmallA044: THREE.Mesh
    Mesh_tree_pineSmallA044_1: THREE.Mesh
    Mesh_tree_pineSmallA045: THREE.Mesh
    Mesh_tree_pineSmallA045_1: THREE.Mesh
    Mesh_tree_pineSmallA046: THREE.Mesh
    Mesh_tree_pineSmallA046_1: THREE.Mesh
    Mesh_tree_pineSmallA047: THREE.Mesh
    Mesh_tree_pineSmallA047_1: THREE.Mesh
    Mesh_tree_pineSmallA048: THREE.Mesh
    Mesh_tree_pineSmallA048_1: THREE.Mesh
    Mesh_tree_pineSmallA049: THREE.Mesh
    Mesh_tree_pineSmallA049_1: THREE.Mesh
    Mesh_tree_pineSmallA050: THREE.Mesh
    Mesh_tree_pineSmallA050_1: THREE.Mesh
    Mesh_tree_pineSmallA051: THREE.Mesh
    Mesh_tree_pineSmallA051_1: THREE.Mesh
    Mesh_tree_pineSmallA052: THREE.Mesh
    Mesh_tree_pineSmallA052_1: THREE.Mesh
    Mesh_tree_pineSmallA053: THREE.Mesh
    Mesh_tree_pineSmallA053_1: THREE.Mesh
    Mesh_tree_pineSmallA055: THREE.Mesh
    Mesh_tree_pineSmallA055_1: THREE.Mesh
    Mesh_tree_pineSmallA057: THREE.Mesh
    Mesh_tree_pineSmallA057_1: THREE.Mesh
    Mesh_tree_pineSmallA058: THREE.Mesh
    Mesh_tree_pineSmallA058_1: THREE.Mesh
    Mesh_tree_pineSmallA059: THREE.Mesh
    Mesh_tree_pineSmallA059_1: THREE.Mesh
    Mesh_tree_pineSmallA060: THREE.Mesh
    Mesh_tree_pineSmallA060_1: THREE.Mesh
    Mesh_tree_pineSmallA061: THREE.Mesh
    Mesh_tree_pineSmallA061_1: THREE.Mesh
    wall: THREE.Mesh
    Triangle: THREE.Mesh
    Bleachers: THREE.Mesh
    Cube009: THREE.Mesh
    Cube009_1: THREE.Mesh
    Cube010: THREE.Mesh
    Cube010_1: THREE.Mesh
    TechVoc: THREE.Mesh
    Yellow_Bldg: THREE.Mesh
    Admin_bldg: THREE.Mesh
    Bautista: THREE.Mesh
    Cube004: THREE.Mesh
    Cube004_1: THREE.Mesh
  }
  materials: {
    leafsGreen: THREE.MeshStandardMaterial
    woodBark: THREE.MeshStandardMaterial
    leafsDark: THREE.MeshStandardMaterial
    woodBarkDark: THREE.MeshStandardMaterial
    ['bldg asset 1']: THREE.MeshStandardMaterial
    triangle: THREE.MeshStandardMaterial
    bleachers: THREE.MeshStandardMaterial
    ['bldg posts.001']: THREE.MeshStandardMaterial
    ['color map']: THREE.MeshStandardMaterial
    ['bldg asset 1.003']: THREE.MeshStandardMaterial
    floor: THREE.MeshStandardMaterial
    ['bldg asset 2']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/new_qcu_map.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[2, 0, 5.7]}>
        <group position={[0, -0.05, 0]}>
          <mesh geometry={nodes.Mesh_tree_fat_darkh.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_fat_darkh_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-3.852, 0, -7.64]} rotation={[Math.PI, 0, Math.PI]} scale={1.1}>
          <mesh geometry={nodes.Mesh_tree_fat_darkh001.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_fat_darkh001_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-5, -0.05, -0.6]}>
          <mesh geometry={nodes.Mesh_tree_fat_darkh002.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_fat_darkh002_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-0.4, -0.05, 2.3]} rotation={[0, -0.96, 0]}>
          <mesh geometry={nodes.Mesh_tree_fat_darkh003.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_fat_darkh003_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[0.2, -0.05, 1.3]}>
          <mesh geometry={nodes.Mesh_tree_fat_darkh004.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_fat_darkh004_1.geometry} material={materials.woodBarkDark} />
        </group>
      </group>
      <group position={[-2.1, 0.05, 7.5]} scale={0.8}>
        <group position={[0.5, -0.05, 0.25]} rotation={[0, -0.873, 0]} scale={1.2}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[0.25, -0.05, -0.375]} rotation={[0, -1.571, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA001.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA001_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[0, -0.05, -0.875]} rotation={[0, -0.96, 0]} scale={1.26}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA002.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA002_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-0.409, -0.05, -0.455]} rotation={[0, -1.134, 0]} scale={1.2}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA003.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA003_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-0.489, -0.05, -1.124]} rotation={[Math.PI, -1.309, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA004.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA004_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-0.601, -0.05, -1.671]} rotation={[0, -1.222, 0]} scale={1.26}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA005.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA005_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[5.274, -0.05, -1.171]} rotation={[Math.PI, -0.611, Math.PI]} scale={1.26}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA010.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA010_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[4.907, -0.05, -0.479]} rotation={[0, 0.698, 0]} scale={1.26}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA007.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA007_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-0.75, -0.05, -3.5]} rotation={[0, -0.873, 0]} scale={1.2}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA011.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA011_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[4.702, -0.05, 0.03]} rotation={[0, -0.175, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA009.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA009_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1, -0.05, -4.125]} rotation={[0, -1.571, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA012.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA012_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.25, -0.05, -4.625]} rotation={[0, -0.96, 0]} scale={1.26}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA013.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA013_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.284, -0.05, -3.705]} rotation={[0, -1.134, 0]} scale={1.2}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA014.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA014_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -5.374]} rotation={[Math.PI, -1.309, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA015.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA015_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-0.114, -0.05, -1.499]} rotation={[Math.PI, -0.436, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA017.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA017_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -5.874]} rotation={[0, -1.134, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA018.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA018_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -6.624]} rotation={[0, -1.571, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA019.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA019_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -6.249]} rotation={[Math.PI, -0.96, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA020.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA020_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -6.999]} rotation={[Math.PI, -1.309, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA021.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA021_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[5.577, -0.05, 1.03]} rotation={[0, 0.262, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA022.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA022_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[5.077, -0.05, 1.03]} rotation={[0, 0.698, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA023.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA023_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[5.407, -0.05, 0.646]} rotation={[0, 0.698, 0]} scale={1.26}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA024.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA024_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[5.386, -0.05, -12.874]} rotation={[Math.PI, -1.309, Math.PI]} scale={1.092}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA025.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA025_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -7.374]} rotation={[Math.PI, -1.309, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA026.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA026_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -7.874]} rotation={[0, -1.134, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA027.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA027_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -8.624]} rotation={[0, -1.571, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA028.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA028_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -8.249]} rotation={[Math.PI, -0.96, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA029.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA029_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -8.999]} rotation={[0, -1.134, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA030.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA030_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -9.749]} rotation={[0, -1.571, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA031.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA031_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -9.374]} rotation={[Math.PI, -0.96, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA032.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA032_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -10.124]} rotation={[Math.PI, -1.309, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA033.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA033_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -10.499]} rotation={[Math.PI, -1.309, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA034.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA034_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -10.999]} rotation={[0, -1.134, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA035.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA035_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -11.749]} rotation={[0, -1.571, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA036.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA036_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -11.374]} rotation={[Math.PI, -0.96, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA037.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA037_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -12.124]} rotation={[0, -1.134, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA038.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA038_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -12.874]} rotation={[0, -1.571, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA039.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA039_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -12.499]} rotation={[Math.PI, -0.96, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA040.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA040_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -13.249]} rotation={[Math.PI, -1.309, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA041.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA041_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -13.624]} rotation={[Math.PI, -1.309, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA042.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA042_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -14.124]} rotation={[0, -1.134, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA043.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA043_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -14.874]} rotation={[0, -1.571, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA044.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA044_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -14.499]} rotation={[Math.PI, -0.96, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA045.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA045_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -15.374]} rotation={[0, -1.134, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA046.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA046_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -16.124]} rotation={[0, -1.571, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA047.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA047_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -15.749]} rotation={[Math.PI, -0.96, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA048.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA048_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -16.499]} rotation={[Math.PI, -1.309, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA049.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA049_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -16.874]} rotation={[Math.PI, -1.309, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA050.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA050_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -17.374]} rotation={[0, -1.134, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA051.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA051_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -18.124]} rotation={[0, -1.571, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA052.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA052_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -17.749]} rotation={[Math.PI, -0.96, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA053.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA053_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -18.624]} rotation={[0, -1.571, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA055.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA055_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -18.999]} rotation={[Math.PI, -1.309, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA057.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA057_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -19.374]} rotation={[Math.PI, -1.309, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA058.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA058_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -19.874]} rotation={[0, -1.134, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA059.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA059_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -20.624]} rotation={[0, -1.571, 0]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA060.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA060_1.geometry} material={materials.woodBarkDark} />
        </group>
        <group position={[-1.489, -0.05, -20.249]} rotation={[Math.PI, -0.96, Math.PI]} scale={0.84}>
          <mesh geometry={nodes.Mesh_tree_pineSmallA061.geometry} material={materials.leafsDark} />
          <mesh geometry={nodes.Mesh_tree_pineSmallA061_1.geometry} material={materials.woodBarkDark} />
        </group>
      </group>
      <mesh geometry={nodes.wall.geometry} material={materials['bldg asset 1']} position={[-0.7, 0.02, 0]} />
      <mesh geometry={nodes.Triangle.geometry} material={materials.triangle} position={[0, 0.02, 5.8]} scale={0.2} />
      <mesh geometry={nodes.Bleachers.geometry} material={materials.bleachers} position={[-0.6, 0.02, 0]} />
      <group position={[3, 0.02, -4.6]} rotation={[0, -1.571, 0]} scale={0.518}>
        <mesh geometry={nodes.Cube009.geometry} material={materials['bldg asset 1']} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['bldg posts.001']} />
      </group>
      <group position={[3, 0.02, -7.3]} rotation={[0, -1.571, 0]} scale={0.602}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['color map']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['bldg asset 1.003']} />
      </group>
      <mesh geometry={nodes.TechVoc.geometry} material={materials['bldg asset 1']} position={[-0.56, 0.02, 0]} />
      <mesh geometry={nodes.Yellow_Bldg.geometry} material={materials['bldg asset 1']} position={[1, 0.02, -2]} />
      <mesh geometry={nodes.Admin_bldg.geometry} material={materials['bldg asset 1']} position={[-1.259, 0.02, -4.72]} />
      <mesh geometry={nodes.Bautista.geometry} material={materials['bldg asset 1']} position={[-1.2, 0.02, -7.5]} scale={[0.9, 1, 1]} />
      <group scale={[8, 1, 9.9]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.floor} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['bldg asset 2']} />
      </group>
      <group position={[-0.78, 0, 5.25]} rotation={[0, -Math.PI / 6, 0]} scale={0.5}>
        <mesh geometry={nodes.Mesh_tree_palmShort.geometry} material={materials.leafsGreen} />
        <mesh geometry={nodes.Mesh_tree_palmShort_1.geometry} material={materials.woodBark} />
      </group>
      <group position={[0.75, 0, 5.25]} rotation={[Math.PI, -1.222, Math.PI]} scale={0.5}>
        <mesh geometry={nodes.Mesh_tree_palmShort001.geometry} material={materials.leafsGreen} />
        <mesh geometry={nodes.Mesh_tree_palmShort001_1.geometry} material={materials.woodBark} />
      </group>
      <group position={[-0.03, 0, 6.82]} rotation={[Math.PI, -0.436, Math.PI]} scale={0.5}>
        <mesh geometry={nodes.Mesh_tree_palmShort002.geometry} material={materials.leafsGreen} />
        <mesh geometry={nodes.Mesh_tree_palmShort002_1.geometry} material={materials.woodBark} />
      </group>
      <group position={[1.6, -0.05, 6.3]}>
        <mesh geometry={nodes.Mesh_tree_oak_dark.geometry} material={materials.leafsDark} />
        <mesh geometry={nodes.Mesh_tree_oak_dark_1.geometry} material={materials.woodBarkDark} />
      </group>
      <group position={[-1.908, 0, -1.26]} rotation={[0, -1.484, 0]} scale={0.7}>
        <mesh geometry={nodes.Mesh_tree_oak_dark001.geometry} material={materials.leafsDark} />
        <mesh geometry={nodes.Mesh_tree_oak_dark001_1.geometry} material={materials.woodBarkDark} />
      </group>
      <group position={[-1.708, 0, -2.56]} rotation={[Math.PI, -Math.PI / 9, Math.PI]} scale={0.7}>
        <mesh geometry={nodes.Mesh_tree_oak_dark002.geometry} material={materials.leafsDark} />
        <mesh geometry={nodes.Mesh_tree_oak_dark002_1.geometry} material={materials.woodBarkDark} />
      </group>
      <group position={[3.5, 0, 0.2]} rotation={[0, -0.175, 0]} scale={1.08}>
        <mesh geometry={nodes.Mesh_tree_oak_dark003.geometry} material={materials.leafsDark} />
        <mesh geometry={nodes.Mesh_tree_oak_dark003_1.geometry} material={materials.woodBarkDark} />
      </group>
      <group position={[-2.6, -0.05, 5.6]}>
        <mesh geometry={nodes.Mesh_tree_oak_dark004.geometry} material={materials.leafsDark} />
        <mesh geometry={nodes.Mesh_tree_oak_dark004_1.geometry} material={materials.woodBarkDark} />
      </group>
      <group position={[-2.2, -0.05, 7.6]} scale={0.8}>
        <mesh geometry={nodes.Mesh_tree_oak_dark005.geometry} material={materials.leafsDark} />
        <mesh geometry={nodes.Mesh_tree_oak_dark005_1.geometry} material={materials.woodBarkDark} />
      </group>
      <group position={[2.1, -0.05, 7.6]}>
        <mesh geometry={nodes.Mesh_tree_oak_dark006.geometry} material={materials.leafsDark} />
        <mesh geometry={nodes.Mesh_tree_oak_dark006_1.geometry} material={materials.woodBarkDark} />
      </group>
      <group position={[-2.9, 0, 7.3]} rotation={[0, -0.175, 0]} scale={1.08}>
        <mesh geometry={nodes.Mesh_tree_oak_dark007.geometry} material={materials.leafsDark} />
        <mesh geometry={nodes.Mesh_tree_oak_dark007_1.geometry} material={materials.woodBarkDark} />
      </group>
      <group position={[-3, 0, 6.6]} rotation={[0, 0.611, 0]} scale={1.188}>
        <mesh geometry={nodes.Mesh_tree_oak_dark008.geometry} material={materials.leafsDark} />
        <mesh geometry={nodes.Mesh_tree_oak_dark008_1.geometry} material={materials.woodBarkDark} />
      </group>
      <group position={[3.7, 0, -0.6]} rotation={[0, -Math.PI / 3, 0]} scale={0.864}>
        <mesh geometry={nodes.Mesh_tree_oak_dark009.geometry} material={materials.leafsDark} />
        <mesh geometry={nodes.Mesh_tree_oak_dark009_1.geometry} material={materials.woodBarkDark} />
      </group>
    </group>
  )
}

useGLTF.preload('/new_qcu_map.glb')
