/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/new_qcu_map.glb --transform 
Files: ./public/models/new_qcu_map.glb [1.38MB] > C:\Users\asphy\Desktop\2nd version\backup\qculand\first_attempt\new_qcu_map-transformed.glb [110.26KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/new_qcu_map-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.wall.geometry} material={materials['bldg asset 1']} position={[-0.7, 0.02, 0]} />
      <mesh geometry={nodes.Triangle.geometry} material={materials.triangle} position={[0, 0.02, 5.8]} scale={0.2} />
      <mesh geometry={nodes.Bleachers.geometry} material={materials.bleachers} position={[-0.6, 0.02, 0]} />
      <mesh geometry={nodes.computer_lab.geometry} material={materials['bldg posts.001']} position={[3, 0.02, -4.6]} rotation={[0, -1.571, 0]} scale={0.518} />
      <group position={[3, 0.02, -7.3]} rotation={[0, -1.571, 0]} scale={0.602}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['color map']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['bldg asset 1.003']} />
      </group>
      <group scale={[8, 1, 9.9]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.floor} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['bldg asset 2']} />
      </group>
      <group position={[-0.78, 0, 5.25]} rotation={[0, -Math.PI / 6, 0]} scale={0.5}>
        <mesh geometry={nodes.Mesh_tree_palmShort.geometry} material={materials.leafsGreen} />
        <mesh geometry={nodes.Mesh_tree_palmShort_1.geometry} material={materials.woodBark} />
      </group>
      <group position={[1.6, -0.05, 6.3]}>
        <mesh geometry={nodes.Mesh_tree_oak_dark.geometry} material={materials.leafsDark} />
        <mesh geometry={nodes.Mesh_tree_oak_dark_1.geometry} material={materials.woodBarkDark} />
      </group>
    </group>
  )
}

useGLTF.preload('/new_qcu_map-transformed.glb')
