/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./map parts/qcu_bldg2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/qcu_bldg2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bautista.geometry} material={materials['bldg asset 1']} rotation={[0, 1.571, 0]} scale={[0.9, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/qcu_bldg2.glb')
