/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./map parts/qcu_bldg1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/qcu_bldg1.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.864}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['bldg asset 1']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['bldg posts']} />
      </group>
    </group>
  )
}

useGLTF.preload('/qcu_bldg1.glb')
