/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./map parts/qcu_bldg2.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bautista: THREE.Mesh
  }
  materials: {
    ['bldg asset 1']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/qcu_bldg2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bautista.geometry} material={materials['bldg asset 1']} rotation={[0, 1.571, 0]} scale={[0.9, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/qcu_bldg2.glb')
