/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./map parts/qcu_bldg1.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_1: THREE.Mesh
    Cube_2: THREE.Mesh
  }
  materials: {
    ['bldg asset 1']: THREE.MeshStandardMaterial
    ['bldg posts']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/qcu_bldg1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.864}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['bldg asset 1']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['bldg posts']} />
      </group>
    </group>
  )
}

useGLTF.preload('/qcu_bldg1.glb')
