/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./map parts/qcu_bldg4.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/qcu_bldg4.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Admin_bldg.geometry} material={materials['bldg asset 1']} />
    </group>
  )
}

useGLTF.preload('/qcu_bldg4.glb')
