/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./map parts/qcu_bldg5.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/qcu_bldg5.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Yellow_Bldg.geometry} material={materials['bldg asset 1']} rotation={[Math.PI, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/qcu_bldg5.glb')
