/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./map parts/qcu_bldg_comp_lab.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/qcu_bldg_comp_lab.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['bldg asset 1']} position={[-1.98, 3.45, 1.693]} scale={[0.28, 0.28, 0.039]} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials['bldg asset 1']} />
      <mesh geometry={nodes.Cube_2.geometry} material={materials['bldg posts']} />
    </group>
  )
}

useGLTF.preload('/qcu_bldg_comp_lab.glb')
